services:
  - type: web
    name: podcast-web-app-backend
    runtime: python
    pythonVersion: 3.11
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend && pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: true
    autoDeploy: true
    rootDir: .
    region: oregon
    plan: free
